services:
  llama:
    container_name: llama
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./model:/app/model
      - ./result:/app/result
      - ./llama.cpp_build:/app/llama.cpp_build
      - ./llama-cpp-python:/app/llama-cpp-python
    environment:
      - OMP_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
    working_dir: /app
    ports:
      - 8001:8001
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
